apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: roboshop
  labels:
    purpose: rabbitmq
    project: roboshop
    tier: database
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    purpose: rabbitmq
    project: roboshop
    tier: database
spec:
  clusterIP: None
  selector:
    purpose: rabbitmq
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    purpose: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    purpose: rabbitmq
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    matchLabels:
      purpose: rabbitmq
      project: roboshop
      tier: database
  serviceName: "rabbitmq-headless"
  replicas: 2
  template:
    metadata:
      labels:
        purpose: rabbitmq
        project: roboshop
        tier: database
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - secretRef:
            name: rabbitmq-secret
        volumeMounts:
        - name: rabbit-data
          mountPath: /var/lib/rabbitmq
      volumeClaimTemplates:
      - metadata:
          name: rabbit-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "roboshop-ebs"
          resources:
            requests:
              storage: 2Gi