apiVersion: v1
kind: Secret
metadata:
  name: mysql-config
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="
---
apiVersion: v1
kind: Service
metadata:
  name: mysqsl-headless
  namespace: roboshop
  labels:
    name: mysql
    project: roboshop
    tier: database
spec:
  clusterIP: None # if ClusterIp is none it comes under headless service
  selector:
    name: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysqsl
  namespace: roboshop
  labels:
    name: mysql
    project: roboshop
    tier: database
spec:
  selector:
    name: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    matchLabels:
      name: mysql
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        name: mysql
        project: roboshop
        tier: database # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: sham6779/mysql:v1
        envFrom:
        - secretRef:
            name: mysql-config
        # ports:
        # - containerPort: 80
        #   name: web
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi