apiVersion: v1
kind: Service
metadata:
  name: mysqsl-headless
  namespace: roboshop
  labels:
    name: redis
    project: roboshop
    tier: database
spec:
  clusterIP: None # if ClusterIp is none it comes under headless service
  selector:
    name: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysqsl
  namespace: roboshop
  labels:
    name: redis
    project: roboshop
    tier: database
spec:
  selector:
    name: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    matchLabels:
      name: redis
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "mysqsl-headless"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        name: redis
        project: roboshop
        tier: database # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: sham6779/mysql:v1
        # ports:
        # - containerPort: 80
        #   name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi